### ISSUE TITLE
Tag for v1.1

### ISSUE THREAD

**Issue by gabrielcox** [uastm/standards#5]
Hi,
Could we create a tag of "astm_rid_api_1.1" ?  I would like to include api in the name to ensure people don't mistaken it for the standard.
Also, can you please include the URL back to the v1.1 API within the YAML itself (perhaps in the description). That way, if this API is viewed in something other that github, then they know how to get back to this.

**Comment by BenjaminPelletier** [comment]
Tag added; this URL now works: https://github.com/uastech/standards/tree/astm_rid_api_2.0

However, most people will probably want this URL (shortlink will be created soon):
https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/uastech/standards/astm_rid_api_2.0/remoteid/canonical.yaml
